Add : account, mypage, order, product 앱 생성 및 models.py 생성
wecode-bootcamp-korea/18-1st-LINEAVENGERS-backend pull request #2
Opened 2021-03-17 12:31 UTC by KIMGYUDONG

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-17 14:04 UTC, ulfrid requested changes
확인 바랍니다. 전체적으로 컨벤션 불량, 오타 다시 확인해 주세요.

2021-03-17 14:04 UTC, devops-andrew commented on account/models.py
> +    password     = models.CharField(max_length=100)
```suggestion
    password     = models.CharField(max_length=300)
```
암호화 고려하면 300 정도로 늘려주세요.

2021-03-17 14:04 UTC, devops-andrew commented on account/models.py
> +    name         = models.CharField(max_length=20)
```suggestion
    name         = models.CharField(max_length=50)
```
이름도 넉넉하게 50자로 해주세요.

2021-03-17 14:04 UTC, devops-andrew commented on account/models.py
> +    user_image   = models.CharField(max_length=2000, null=True)
```suggestion
    image_url   = models.URLField(max_length=2000, null=True)
```
강제성은 없지만 URLField 라는 것도 있습니다. 가독성을 위해 사용해주세요.
테이블 명에 해당하는 단어를 컬럼에 중복해서 넣을 필요는 없을 것 같습니다.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +    point = models.IntegerField()
```suggestion
    point = models.IntegerField(default=0)
```
포인트는 혹시 음수로도 변하나요? 아니라면 PositiveIntegerField라는 것도 있으니 참고하세요.
그리고 인티저 필드등을 쓸때는 보통 디폴트 값을 설정해주세요.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +    update_at = models.DateField(auto_now=True)
```suggestion
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
```

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +    update_at = models.DateField(auto_now=True)
아래 다른 것들도 바꿔주세요.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +    update_at = models.DateField(auto_now=True)
한가지 의문사항은 시간정보를 전부다 DateField로 관리하시는데 일부러 날짜만 처리하시는건가요?
아니라면 DateTimeField로 변경해주세요.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +class Review_image(models.Model):
```suggestion
class ReviewImage(models.Model):
```
클래스는 Pascal Case로 하셔야 합니다.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +    reviw     = models.ForeignKey(Review, on_delete=models.CASCADE, null=True)
```suggestion
    review     = models.ForeignKey(Review, on_delete=models.CASCADE, null=True)
```
오타 수정해주세요.

2021-03-17 14:04 UTC, devops-andrew commented on mypage/models.py
> +class Review_recommand(models.Model):
```suggestion
class ReviewRecommand(models.Model):
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +class Order_address(models.Model):
```suggestion
class Address(models.Model):
```
그냥 Address가 나을것 같은데요~!

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +        db_table = "order_addresses"
```suggestion
        db_table = "addresses"
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +class Order_status(models.Model):
```suggestion
class OrderStatus(models.Model):
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +class Pay_type(models.Model):
```suggestion
class PayType(models.Model):
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +    order_at     = models.DateField(auto_now_add=True)
```suggestion
    created_at     = models.DateField(auto_now_add=True)
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +    order_status = models.ForeignKey(Order_status, on_delete=models.CASCADE, null=True)
```suggestion
    order_status = models.ForeignKey(OrderStatus, on_delete=models.CASCADE, null=True)
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +    address      = models.ForeignKey(Order_address, on_delete=models.CASCADE, null=True)
```suggestion
    address      = models.ForeignKey(OrderAddress, on_delete=models.CASCADE, null=True)
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +        db_table = "order_products"
아래에 카트는 필요 없을 것 같은데 이 클래스의 이름을 Cart로 하면 안되나요?

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +class Order_product(models.Model):
```suggestion
class OrderProduct(models.Model):
```

2021-03-17 14:04 UTC, devops-andrew commented on order/models.py
> +    quantity      = models.IntegerField()
```suggestion
    quantity      = models.PositiveIntegerField(default=0)
```

2021-03-17 14:04 UTC, ulfrid commented on order/models.py
> +    pay_at   = models.DateField(auto_now_add=True)
```suggestion
    created_at   = models.DateField(auto_now_add=True)
```
엔터티에 맞춰서 변경하는것도 좋지만 이런부분은 통일하는게 오히려 관리상 편합니다.

2021-03-17 14:04 UTC, ulfrid commented on product/models.py
> +class Product_image(models.Model):
```suggestion
class ProductImage(models.Model):
```

2021-03-17 14:04 UTC, ulfrid commented on order/models.py
> +        db_table = "carts"
제거해주세요 심지어 프로덕트는 걸려있지도 않네요.

2021-03-18 01:32 UTC, KIMGYUDONG commented on mypage/models.py
> +    update_at = models.DateField(auto_now=True)
아니요,, 수정하겠습니다. 감사합니다!

2021-03-18 01:59 UTC, KIMGYUDONG commented on order/models.py
> +        db_table = "order_products"
넵! 아래 Cart를 삭제하고 이 클래스 이름을 Cart로 변경했습니다!

2021-03-18 02:03 UTC, KIMGYUDONG commented on order/models.py
> +        db_table = "carts"
넵 제거했고, ProductOrder를 Cart로 변경 후 Product를 걸었습니다/

2021-03-18 04:36 UTC, KIMGYUDONG commented
지훈님! 늦은 시간인데도 이렇게 꼼꼼하게 봐주셨네요,, 감사합니다,, 
max_length랑 클래스명 정할때 언더스코어부분이 모호했었는데 덕분에 어떻게 해결할지 알겠습니다.
그리고 장고 model field를 좀 더 신경써서 하겠습니당. 
감사합니다!!

2021-03-18 04:37 UTC, KIMGYUDONG commented on account/models.py
> +    user_image   = models.CharField(max_length=2000, null=True)
넵 수정했습니다. 감사합니다.

2021-03-18 06:27 UTC, ulfrid requested changes
해당 부분 의도 설명 부탁드립니다.

2021-03-18 06:27 UTC, ulfrid commented on order/models.py
> +    is_order = models.BooleanField(default=False)
설명해주세요~!

2021-03-18 08:36 UTC, KIMGYUDONG commented on order/models.py
> +    is_order = models.BooleanField(default=False)
넵 지훈님. 
우선 `quantity`필드는 양수만 올수 있게끔 `IntegerField`에서 `PositiveIntegerField`로 변경하였습니다.
그리고, `is_order`필드는 장바구니에 담긴 값이 주문이 되었는지와 주문이 안된경우를 분리하여, 주문이 안된 경우면 값을 `false`로 두어 장바구니 페이지에 해당 상품이 계속 보이게하고, 주문이 된경우면 값을 `true`로 두어 장바구니 페이지에 해당 상품이 안보이고, 주문id를 통해 주문에 대한 상품을 볼 수있게끔 하려 하였습니다. 이 값이 없으면 주문페이지에서 해당 주문에 대한 상품을 조회하는게 어려울 거같아 추가하였습니다!!
추가적인 확인 감사드립니다!!

2021-03-18 10:43 UTC, ulfrid commented on order/models.py
> +    is_order = models.BooleanField(default=False)
이 부분은 전에 설명 드렸듯이 order_status로 관리 되기 때문에 이 요소가 필요 없을 것 같습니다.

2021-03-19 01:32 UTC, ulfrid commented
LGTM 👍

2021-03-19 01:32 UTC, merged