[김규동] feature/account에서 models.py 수정 후 푸시 [URGENT]
wecode-bootcamp-korea/18-1st-LINEAVENGERS-backend pull request #4
Opened 2021-03-19 11:37 UTC by KIMGYUDONG

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- feature/account에서 models.py 수정 후 푸시
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- feature/fix_model 삭제
- menu클래스와 category클래스에 no컬럼 추가
- 마이그래이션
- address클래스와 review클래스 필드수정
-
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-20 08:37 UTC, ulfrid requested changes
우리가 리스판스에서 메세지를 쓰는 이유는 이미 status 코드만으로도 충분하지만 위의 코드 중 같은 400을 놓고 본다면 결국 프론트 코드에서 3개의 400중 정확한 에러가 무엇인지 Validation하려면 각각의 메세지를 비교해야하는데, 비효율 적입니다.
그래서 가이드에서 추천드리는 INVALID_KEYS, USER_DOES_NOT_EXIST 등의 영문 대문자 및 언더스코어로 단어 구분을 하는 일종의 에러에대한 문자코드를 만들어서 관리하는 것입니다.
우리는 프론트 코드와 통신을 하는것이지 실제로 고객과 대면하지 않습니다. 따라서 이러한 메세지 명명은 지양하는게 좋습니다. 꼭 메세지를 써야 한다면 위의 식별하는 코드를 따로 주고, 그에대한 메세지를 같이 제공해서 그 메세지를 프론트에서 사용하게 하는게 맞습니다.

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +
```suggestion
            User.objects.create(
                login_id=login_id, 
                password=password, 
                name=name, 
                phone_number=phone_number,
                email=email
            )
```

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +            if len(password) < 8:
```suggestion
            if len(password) < MIN_PASSWORD_LENGTH:
```
8과 같은 비교값은 하드코딩 하지말고 상수로 지정해서 임포트 최 하단에 작성해주세요.

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +                return JsonResponse({"message":"No TUCKSOOMUNJA"}, status = 400)
```suggestion
                return JsonResponse({"message":"INVALID_CHARACTER"}, status = 400)
```
이런게 낫겠죠?

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +                return JsonResponse({"message":"More than 8 letters PLEASE."}, status = 400)
```suggestion
                return JsonResponse({"message":"SHORT_PASSWORD"}, status = 400)
```

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +                return JsonResponse({"message":"Put @ and . in email PLEASE."}, status = 400)
```suggestion
                return JsonResponse({"message":"INVALID_EMAIL"}, status = 400)
```

2021-03-20 08:37 UTC, ulfrid commented on account/views.py
> +            return JsonResponse({"message": "json.decoder.JSONDecodeError"}, status = 400)
```suggestion
            return JsonResponse({"message": "INVALID_JSON"}, status = 400)
```

2021-03-20 11:12 UTC, KIMGYUDONG commented on account/views.py
> +
오 훨씬 더 깔끔해졌네요..
앞으론 줄줄이 쓰지않고 엔터 치면서 쓰겠습니다. 감사합니다!!

2021-03-20 11:14 UTC, KIMGYUDONG commented on account/views.py
> +            if len(password) < 8:
비교값은 상수로 지정해서 임포트 최하단.. 메모.. 하겠습니다!!

2021-03-20 11:16 UTC, KIMGYUDONG commented on account/views.py
> +                return JsonResponse({"message":"No TUCKSOOMUNJA"}, status = 400)
부끄럽네요,, 급하게 커밋하고 푸시하느라,, ㅠ
감사합니다!!

2021-03-20 11:17 UTC, KIMGYUDONG commented on account/views.py
> +                return JsonResponse({"message":"More than 8 letters PLEASE."}, status = 400)
제가 지금까지 메시지를 문장으로 적었는데 고치겠습니다. 훨씬 깔끔하고 알아듣기 좋네요. 감사합니다!!

2021-03-20 11:17 UTC, KIMGYUDONG commented on account/views.py
> +                return JsonResponse({"message":"Put @ and . in email PLEASE."}, status = 400)
증말루 깔끔하네요..

2021-03-20 11:18 UTC, KIMGYUDONG commented on account/views.py
> +            return JsonResponse({"message": "json.decoder.JSONDecodeError"}, status = 400)
에러명도 깔끔하게 INVALID_ 로 하겠습니다!!

2021-03-21 01:58 UTC, ulfrid commented
LGTM👍

2021-03-21 01:58 UTC, merged

2021-03-21 09:23 UTC, KIMGYUDONG commented
헉 일요일인데도 봐주셨네요.. 감사합니다!!
기능별로 브랜치 옮겨가면서 작업하는게 처음이라 많이 서툴렀네요..
깃 공부 많이하겠습니다, 감사합니다!