[김규동] 좋아요 기능 추가, 리뷰 쓰기 기능 추가 / 리뷰 보기 기능 진행중
wecode-bootcamp-korea/18-1st-LINEAVENGERS-backend pull request #9
Opened 2021-03-22 12:44 UTC by KIMGYUDONG

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 좋아요 기능 추가
- 리뷰 쓰기 기능 추가 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- mypage/views.py 의 `FavoriteCreate`에 좋아요 기능 작성.
좋아요 버튼을 누른 유저아이디가 `Favorite`클래스에 없다면 추가 후 is_favorite를 True로 변경.
좋아요 버튼을 누른 유저아이디가 `Favorite`클래스가 있다면 그 유저의 is_favorite가 True면 False로 변경, False면 True로 변경
-  mypage/views.py 에 `ReviewClick`, `ReviewCreate`생성. 라인프렌즈 홈페이지에서 리뷰쓰기 팝업 버튼을 누르면 `ReviewClick`로 프론트앤드에 상품의 name과 image를 전달. 리뷰작성 완료 버튼을 누르면 `ReviewCreate`로 `Review`클래스에 정보 저장.  

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-22 16:08 UTC, ulfrid requested changes
확인 바랍니다. 내일 만나서 해결할 것들이 좀 많네요. 수고하셨습니다. 내일 잠시 봬요

2021-03-22 16:08 UTC, ulfrid commented on mypage/urls.py
> +    path('/reviewclick', ReviewClick.as_view()),
api 경로에는 동사가 들어가면 안됩니다. create, click 그에 따른 뷰 클래스도 다 문제가 있죠?

2021-03-22 16:08 UTC, ulfrid commented on mypage/views.py
> +class FavoriteCreate(View):
이렇게 명칭을 쓰면 생성하는 메서드 하나만 있어야 할것 같지 않나요?

2021-03-22 16:08 UTC, ulfrid commented on mypage/views.py
> +        user    = User.objects.get(id=user)
이건 회원가입 유무와 상관있는것 같은데, 그렇다면 데코레이터 적용해주세요.

2021-03-23 04:35 UTC, KIMGYUDONG commented on mypage/urls.py
> +    path('/reviewclick', ReviewClick.as_view()),
넵 알겠습니다. 레스트풀 하지않네요,, 수정하겠습니다. 감사합니다!

2021-03-24 05:06 UTC, KIMGYUDONG commented on mypage/views.py
> +class FavoriteCreate(View):
명칭을 FavoriteView로 수정한 후 매서드 post, get으로 찜하기와 찜한 리스트 불러오기 두개를 구현하도록 수정했습니다!

2021-03-24 05:06 UTC, KIMGYUDONG commented on mypage/views.py
> +        user    = User.objects.get(id=user)
넵! 데코레이터 주석처리 삭제후 적용했습니다!

2021-03-24 05:13 UTC, ulfrid requested changes
확인 바랍니다

2021-03-24 05:13 UTC, ulfrid commented on account/views.py
> +            return JsonResponse({"message":"INVALID_KEY"},  status = 400)/review
이거 뭐에요?
```suggestion
            return JsonResponse({"message":"INVALID_KEY"},  status = 400)/review <<<????
```

2021-03-24 05:20 UTC, KIMGYUDONG commented on account/views.py
> +            return JsonResponse({"message":"INVALID_KEY"},  status = 400)/review
엇 수정했습니다. 어제 회원가입 로그인 통신하다가 잘못 누른것 같습니다.. feature/account 브랜치에는 /review가 없습니다,,

2021-03-24 05:59 UTC, merged

2021-03-24 05:59 UTC, ulfrid commented
하나의 브랜치에서 여러가지 할지 말아주세요. LGTM 👍